In [1]:
import pandas as pd
import numpy as np
import random

In [2]:
class player:
    def __init__(self):
        self.final_result = ["B", "I", "N", "G", "O"]
        self.full_list = [num for num in range(1, 26)]
        random.shuffle(self.full_list)
        self.grid = np.reshape(self.full_list, newshape=(5,5))
        self.bool_grid = np.zeros((5,5))
        self.bool_grid = self.bool_grid == 1
        self.message = ""
        self.dup_grid = []
        for i in range(5):
            row = []
            for j in range(5):
                row.append(str(self.grid[i,j]).zfill(2))
            self.dup_grid.append(row)
        
    def update_bool_grid(self, user_input):
        i, j = np.transpose((self.grid == user_input).nonzero())[0]
        self.bool_grid[i, j] = True
        self.dup_grid[i][j] = "**"
    
    def player_turn(self, user_input):
        self.update_bool_grid(user_input)
        counter = self.bingo_counter()
        message = ""
        if counter > 0:
            self.message = "".join(self.final_result[:counter])
    
    def bingo_counter(self):
        counter = 0
        on_diag = []
        off_diag = []
        for i in range(5):
            if sum(self.bool_grid[i,:]) == 5:
                counter += 1
            if sum(self.bool_grid[:, i]) == 5:
                counter += 1
            on_diag.append(self.bool_grid[i,i])
            off_diag.append(self.bool_grid[i, 4-i])
        if sum(on_diag) == 5:
            counter += 1
        if sum(off_diag) == 5:
            counter += 1
        return counter
    
    def print_grid(self):
        for i, row in enumerate(self.bool_grid):
            for j, column in enumerate(row):
                if column:
                    print("|**", end="")
                else:
                    print(f"|{self.dup_grid[i][j]}", end="")
            print("|")

In [3]:
class turn:
    def __init__(self):
        self.user_input_list = [num for num in range(1, 26)]
        
    def auto_choice(self):
        user_input = random.choices(self.user_input_list, k=1)[0]
        self.user_input_list = list(set(self.user_input_list) - set([user_input]))
        return user_input
    
    def user_choice(self):
        user_input = int(input("Enter a number: "))
        self.user_input_list = list(set(self.user_input_list) - set([user_input]))
        return user_input

In [4]:
A = player()
B = player()
turns = turn()

In [5]:
first_player = "A"
user = "B"

In [6]:
if first_player == "A":
    turns_ = ["A", "B"]
    players = [A, B]
else:
    turns_ = ["B", "A"]
    players = [B, A]

In [7]:
if first_player == user:
    print(players[0].grid)
else:
    print(players[1].grid)

[[ 7  2 10  5 12]
 [ 9 14 20  6 22]
 [21 19  3 17 18]
 [24 25  4 13 23]
 [ 1 15  8 11 16]]


In [8]:
turn_number = 0
flag = 0
while flag==0:
    player_ = turn_number % 2
    turn_number += 1
    player_name = turns_[player_]
    if player_name == user:
        user_choice = turns.user_choice()
    else:
        user_choice = turns.auto_choice()
    players[0].player_turn(user_choice)
    players[1].player_turn(user_choice)
    if (first_player == user):
        players[0].print_grid()
    else:
        players[1].print_grid()
    print()
    if players[player_].message == "BINGO":
        if player_name == user:
            print("You Win")
        else:
            print("Computer Wins")
        flag = 1

|07|02|10|05|12|
|09|14|20|06|22|
|21|19|03|17|18|
|24|25|**|13|23|
|01|15|08|11|16|



Enter a number:  16


|07|02|10|05|12|
|09|14|20|06|22|
|21|19|03|17|18|
|24|25|**|13|23|
|01|15|08|11|**|

|07|02|10|05|**|
|09|14|20|06|22|
|21|19|03|17|18|
|24|25|**|13|23|
|01|15|08|11|**|



Enter a number:  01


|07|02|10|05|**|
|09|14|20|06|22|
|21|19|03|17|18|
|24|25|**|13|23|
|**|15|08|11|**|

|07|02|10|05|**|
|09|14|20|06|22|
|21|19|03|17|18|
|24|**|**|13|23|
|**|15|08|11|**|



Enter a number:  07


|**|02|10|05|**|
|09|14|20|06|22|
|21|19|03|17|18|
|24|**|**|13|23|
|**|15|08|11|**|

|**|02|10|05|**|
|09|14|**|06|22|
|21|19|03|17|18|
|24|**|**|13|23|
|**|15|08|11|**|



Enter a number:  03


|**|02|10|05|**|
|09|14|**|06|22|
|21|19|**|17|18|
|24|**|**|13|23|
|**|15|08|11|**|

|**|02|10|05|**|
|09|14|**|06|22|
|21|19|**|17|18|
|24|**|**|**|23|
|**|15|08|11|**|



Enter a number:  06


|**|02|10|05|**|
|09|14|**|**|22|
|21|19|**|17|18|
|24|**|**|**|23|
|**|15|08|11|**|

|**|02|10|05|**|
|09|14|**|**|22|
|21|19|**|**|18|
|24|**|**|**|23|
|**|15|08|11|**|



Enter a number:  14


|**|02|10|05|**|
|09|**|**|**|22|
|21|19|**|**|18|
|24|**|**|**|23|
|**|15|08|11|**|

|**|02|10|05|**|
|09|**|**|**|22|
|21|19|**|**|18|
|24|**|**|**|23|
|**|15|**|11|**|



Enter a number:  22


|**|02|10|05|**|
|09|**|**|**|**|
|21|19|**|**|18|
|24|**|**|**|23|
|**|15|**|11|**|

|**|02|10|05|**|
|09|**|**|**|**|
|21|19|**|**|18|
|24|**|**|**|23|
|**|15|**|**|**|



Enter a number:  09


|**|02|10|05|**|
|**|**|**|**|**|
|21|19|**|**|18|
|24|**|**|**|23|
|**|15|**|**|**|

|**|02|10|05|**|
|**|**|**|**|**|
|21|19|**|**|18|
|24|**|**|**|23|
|**|**|**|**|**|



Enter a number:  10


|**|02|**|05|**|
|**|**|**|**|**|
|21|19|**|**|18|
|24|**|**|**|23|
|**|**|**|**|**|

You Win


Enter a number:  5


5